[package]
name = "rite-protocols"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
russh = { workspace = true }
russh-keys = { workspace = true }
suppaftp = { workspace = true, optional = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[features]
default = ["ssh"]
ssh = []
ftp = ["suppaftp"]
all = ["ssh", "ftp"]
